
import fs from 'fs';
import { Code2, ExternalLink, Package, RefreshCw } from 'lucide-react';
import Link from 'next/link';
import path from 'path';

export default function SandboxPage() {
  const sandboxDir = path.join(process.cwd(), 'src', 'app', 'sandbox');
  let projects: string[] = [];

  try {
    if (fs.existsSync(sandboxDir)) {
      const items = fs.readdirSync(sandboxDir, { withFileTypes: true });
      projects = items
        .filter(item => item.isDirectory())
        .map(item => item.name);
    }
  } catch (error) {
    console.error("Failed to read sandbox directory:", error);
  }

    return (
    <div className="flex-1 space-y-8 p-8 min-h-full">
      <div className="max-w-7xl mx-auto space-y-12">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-white/10 pb-8">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold text-white flex items-center gap-3">
              <span className="p-2 rounded-xl bg-primary/10 text-primary">
                <Package className="w-8 h-8" />
              </span>
              <span className="text-primary-glow">ArtorIA</span> Sandbox
            </h1>
            <p className="text-muted-foreground text-lg max-w-2xl">
              Ambiente de execução isolado para aplicações autônomas geradas pelo Arquiteto.
              Aqui nascem as ideias.
            </p>
          </div>
          <button className="p-3 bg-white/5 hover:bg-white/10 rounded-full transition-colors border border-white/10 group">
             <RefreshCw className="w-6 h-6 text-muted-foreground group-hover:text-white transition-all" />
          </button>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {projects.length > 0 ? (
            projects.map((project) => (
              <div 
                key={project} 
                className="group relative bg-card/40 border border-white/5 rounded-2xl p-6 hover:border-primary/30 transition-all duration-300 hover:shadow-2xl hover:shadow-primary/10"
              >
                <div className="absolute top-0 right-0 p-6 opacity-0 group-hover:opacity-100 transition-opacity">
                    <ExternalLink className="w-5 h-5 text-muted-foreground" />
                </div>

                <div className="space-y-4">
                  <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center border border-white/5 group-hover:scale-110 transition-transform">
                    <Code2 className="w-6 h-6 text-primary" />
                  </div>
                  
                  <div>
                    <h2 className="text-2xl font-semibold text-white group-hover:text-primary-glow transition-colors">
                      {project}
                    </h2>
                    <p className="text-sm text-muted-foreground mt-1">
                      Next.js App Router • Autogenerated
                    </p>
                  </div>

                  <div className="pt-4 flex gap-3">
                    <Link 
                      href={`/sandbox/${project}`}
                      className="flex-1 bg-white/5 hover:bg-primary hover:text-white text-muted-foreground py-2.5 rounded-lg text-center text-sm font-medium transition-all duration-300 border border-white/5 hover:border-transparent flex items-center justify-center gap-2"
                    >
                      <ExternalLink className="w-4 h-4" />
                      Open App
                    </Link>
                  </div>
                </div>
              </div>
            ))
          ) : (
            <div className="col-span-full py-20 text-center border border-white/5 border-dashed rounded-2xl bg-card/20">
              <Package className="w-16 h-16 text-muted-foreground mx-auto mb-4" />
              <h3 className="text-xl font-medium text-white">Nenhum projeto encontrado</h3>
              <p className="text-muted-foreground mt-2">
                Peça ao ArtorIA: "Crie um app de Tarefas" para começar.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
