
import fs from 'fs';
import { Code2, ExternalLink, Package, RefreshCw } from 'lucide-react';
import Link from 'next/link';
import path from 'path';

export default function SandboxPage() {
  const sandboxDir = path.join(process.cwd(), 'src', 'app', 'sandbox');
  let projects: string[] = [];

  try {
    if (fs.existsSync(sandboxDir)) {
      const items = fs.readdirSync(sandboxDir, { withFileTypes: true });
      projects = items
        .filter(item => item.isDirectory())
        .map(item => item.name);
    }
  } catch (error) {
    console.error("Failed to read sandbox directory:", error);
  }

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white p-8 font-sans">
      <div className="max-w-7xl mx-auto space-y-12">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-white/10 pb-8">
          <div className="space-y-2">
            <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent flex items-center gap-3">
              <Package className="w-10 h-10 text-blue-400" />
              ArtorIA Sandbox
            </h1>
            <p className="text-gray-400 text-lg max-w-2xl">
              Ambiente de execução isolado para aplicações autônomas geradas pelo Arquiteto.
              Aqui nascem as ideias.
            </p>
          </div>
          <button className="p-3 bg-white/5 hover:bg-white/10 rounded-full transition-colors border border-white/10 group">
             <RefreshCw className="w-6 h-6 text-gray-400 group-hover:text-white transition-all" />
          </button>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {projects.length > 0 ? (
            projects.map((project) => (
              <div 
                key={project} 
                className="group relative bg-[#111] border border-white/5 rounded-2xl p-6 hover:border-blue-500/30 transition-all duration-300 hover:shadow-2xl hover:shadow-blue-500/10"
              >
                <div className="absolute top-0 right-0 p-6 opacity-0 group-hover:opacity-100 transition-opacity">
                    <ExternalLink className="w-5 h-5 text-gray-400" />
                </div>

                <div className="space-y-4">
                  <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-blue-500/20 to-purple-500/20 flex items-center justify-center border border-white/5 group-hover:scale-110 transition-transform">
                    <Code2 className="w-6 h-6 text-blue-400" />
                  </div>
                  
                  <div>
                    <h2 className="text-2xl font-semibold text-gray-100 group-hover:text-blue-400 transition-colors">
                      {project}
                    </h2>
                    <p className="text-sm text-gray-500 mt-1">
                      Next.js App Router • Autogenerated
                    </p>
                  </div>

                  <div className="pt-4 flex gap-3">
                    <Link 
                      href={`/sandbox/${project}`}
                      className="flex-1 bg-white/5 hover:bg-blue-600 hover:text-white text-gray-300 py-2.5 rounded-lg text-center text-sm font-medium transition-all duration-300 border border-white/5 hover:border-transparent flex items-center justify-center gap-2"
                    >
                      <ExternalLink className="w-4 h-4" />
                      Open App
                    </Link>
                  </div>
                </div>
              </div>
            ))
          ) : (
            <div className="col-span-full py-20 text-center border border-white/5 border-dashed rounded-2xl bg-white/5">
              <Package className="w-16 h-16 text-gray-600 mx-auto mb-4" />
              <h3 className="text-xl font-medium text-gray-300">Nenhum projeto encontrado</h3>
              <p className="text-gray-500 mt-2">
                Peça ao ArtorIA: "Crie um app de Tarefas" para começar.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
